server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  h2:
    console:
      path: /h2-console
      enabled: true
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"




