server:
  port: 8090
spring:
  application:
    name: loans
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"

  profiles:
    active:
      - "qa"
build:
  version: "1.0"

loans:
  message: "Welcome to the loans API of EazyBank"
  contactDetails:
    name: "GS - Dev"
    email: "gs@loan.eazybank"
  onCallSupport:
    - (111)666-666
    - (111)777-777





