build:
  version: "1.0"
accounts:
  message: "Welcome to Eazybank account"
  contactDetails:
    name: "Gs - Developer"
    email: "Gs@eazybank.com"
  onCallSupport:
    -(111)111-111
    -(111)000-000


