build:
  version: "1.2"

loans:
  message: "Welcome to the loans API of EazyBank"
  contactDetails:
    name: "GS - Prod"
    email: "gs@loan.eazybank"
  onCallSupport:
    - (111)123-123
    - (111)321-321