spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: "2.0"
accounts:
  message: "Welcome to Eazybank account QA Api"
  contactDetails:
    name: "Gs - QA"
    email: "Gs@eazybank.com"
  onCallSupport:
    -(111)122-222
    -(111)333-333